ALTER TABLE folders
ADD COLUMN created TIMESTAMP DEFAULT NOW(),
ADD COLUMN updated TIMESTAMP DEFAULT NOW(),
ADD COLUMN shared TIMESTAMP DEFAULT NULL;

UPDATE folders SET shared = NOW() WHERE "folders".status = 'shared';