create table editor_notes
(
    id             bigint generated by default as identity primary key,
    draft_id       bigint      not null,
    draft_revision int         not null,
    note           text        not null,
    user_id        text        not null,
    status         text        not null,
    other_statuses text[]      not null,
    timestamp      timestamptz not null
);

create index editor_notes_user_id_idx on editor_notes (user_id);

insert
into editor_notes(draft_id, draft_revision, note, user_id, status, other_statuses, timestamp)
select drafts.article_id,
       drafts.revision,
       notes ->> 'note',
       notes ->> 'user',
       notes -> 'status' ->> 'current',
       array(select jsonb_array_elements_text(coalesce(notes -> 'status' -> 'other', '[]'))),
       (notes ->> 'timestamp')::timestamptz
from (select distinct on
    (article_id,
    revision) article_id,
              revision,
              document
      from articledata
      where document is not null
      order by article_id,
               revision desc) drafts
         cross join lateral jsonb_array_elements(drafts.document -> 'notes') as notes
order by drafts.revision;

alter table articledata
    add column updated_by             text,
    add column responsible            text,
    add column responsible_updated_at timestamptz;

update articledata
set updated_by             = document ->> 'updatedBy',
    responsible            = document -> 'responsible' ->> 'responsibleId',
    responsible_updated_at = (document -> 'responsible' ->> 'lastUpdated')::timestamptz
where document is not null;
