addSbtPlugin("org.typelevel"     % "sbt-tpolecat"       % "0.5.2")
addSbtPlugin("com.earldouglas"   % "xsbt-web-plugin"    % "4.2.4")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"       % "2.2.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("com.scalatsi"      % "sbt-scala-tsi"      % "0.8.3")
addSbtPlugin("com.github.sbt"    % "sbt-git"            % "2.0.1")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"         % "1.11.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scala3-migrate" % "0.7.0")
