
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./article-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAllErrors = schemas["AllErrors"];
export type IArticleContentV2DTO = schemas["ArticleContentV2DTO"];
export type IArticleIdV2DTO = schemas["ArticleIdV2DTO"];
export type IArticleIdsDTO = schemas["ArticleIdsDTO"];
export type IArticleIntroductionDTO = schemas["ArticleIntroductionDTO"];
export type IArticleMetaDescriptionDTO = schemas["ArticleMetaDescriptionDTO"];
export type IArticleMetaImageDTO = schemas["ArticleMetaImageDTO"];
export type IArticleSearchParamsDTO = schemas["ArticleSearchParamsDTO"];
export type IArticleSummaryV2DTO = schemas["ArticleSummaryV2DTO"];
export type IArticleTagDTO = schemas["ArticleTagDTO"];
export type IArticleTitleDTO = schemas["ArticleTitleDTO"];
export type IArticleV2DTO = schemas["ArticleV2DTO"];
export type IAuthorDTO = schemas["AuthorDTO"];
export type IContributorType = schemas["ContributorType"];
export type ICopyrightDTO = schemas["CopyrightDTO"];
export type IDisclaimerDTO = schemas["DisclaimerDTO"];
export type IErrorBody = schemas["ErrorBody"];
export type ILicenseDTO = schemas["LicenseDTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type IRelatedContentLinkDTO = schemas["RelatedContentLinkDTO"];
export type IRequiredLibraryDTO = schemas["RequiredLibraryDTO"];
export type ISearchResultV2DTO = schemas["SearchResultV2DTO"];
export type ISort = schemas["Sort"];
export type ITagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
export type IVisualElementDTO = schemas["VisualElementDTO"];
