// This file is generated automatically. Do not edit.
import * as openapi from "./article-api-openapi";
type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type ArticleContentV2DTO = schemas["ArticleContentV2DTO"];
export type ArticleIdV2DTO = schemas["ArticleIdV2DTO"];
export type ArticleIdsDTO = schemas["ArticleIdsDTO"];
export type ArticleIntroductionDTO = schemas["ArticleIntroductionDTO"];
export type ArticleMetaDescriptionDTO = schemas["ArticleMetaDescriptionDTO"];
export type ArticleMetaImageDTO = schemas["ArticleMetaImageDTO"];
export type ArticleSearchParamsDTO = schemas["ArticleSearchParamsDTO"];
export type ArticleSummaryV2DTO = schemas["ArticleSummaryV2DTO"];
export type ArticleTagDTO = schemas["ArticleTagDTO"];
export type ArticleTitleDTO = schemas["ArticleTitleDTO"];
export type ArticleTrait = schemas["ArticleTrait"];
export type ArticleV2DTO = schemas["ArticleV2DTO"];
export type AuthorDTO = schemas["AuthorDTO"];
export type ContributorType = schemas["ContributorType"];
export type CopyrightDTO = schemas["CopyrightDTO"];
export type DisclaimerDTO = schemas["DisclaimerDTO"];
export type ErrorBody = schemas["ErrorBody"];
export type LicenseDTO = schemas["LicenseDTO"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type RelatedContentLinkDTO = schemas["RelatedContentLinkDTO"];
export type RequiredLibraryDTO = schemas["RequiredLibraryDTO"];
export type SearchResultV2DTO = schemas["SearchResultV2DTO"];
export type Sort = schemas["Sort"];
export type TagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
export type VisualElementDTO = schemas["VisualElementDTO"];
