// This file is generated automatically. Do not edit.
import * as openapi from "./audio-api-openapi";
type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type AudioDTO = schemas["AudioDTO"];
export type AudioMetaInformationDTO = schemas["AudioMetaInformationDTO"];
export type AudioSummaryDTO = schemas["AudioSummaryDTO"];
export type AudioSummarySearchResultDTO = schemas["AudioSummarySearchResultDTO"];
export type AuthorDTO = schemas["AuthorDTO"];
export type ContributorType = schemas["ContributorType"];
export type CopyrightDTO = schemas["CopyrightDTO"];
export type CoverPhotoDTO = schemas["CoverPhotoDTO"];
export type DescriptionDTO = schemas["DescriptionDTO"];
export type ErrorBody = schemas["ErrorBody"];
export type LicenseDTO = schemas["LicenseDTO"];
export type ManuscriptDTO = schemas["ManuscriptDTO"];
export type MetaDataAndFileForm = schemas["MetaDataAndFileForm"];
export type MetaDataAndOptFileForm = schemas["MetaDataAndOptFileForm"];
export type NewAudioMetaInformationDTO = schemas["NewAudioMetaInformationDTO"];
export type NewPodcastMetaDTO = schemas["NewPodcastMetaDTO"];
export type NewSeriesDTO = schemas["NewSeriesDTO"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type PodcastMetaDTO = schemas["PodcastMetaDTO"];
export type SearchParamsDTO = schemas["SearchParamsDTO"];
export type SeriesDTO = schemas["SeriesDTO"];
export type SeriesSearchParamsDTO = schemas["SeriesSearchParamsDTO"];
export type SeriesSummaryDTO = schemas["SeriesSummaryDTO"];
export type SeriesSummarySearchResultDTO = schemas["SeriesSummarySearchResultDTO"];
export type Sort = schemas["Sort"];
export type TagDTO = schemas["TagDTO"];
export type TagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type TitleDTO = schemas["TitleDTO"];
export type TranscriptionResultDTO = schemas["TranscriptionResultDTO"];
export type UpdatedAudioMetaInformationDTO = schemas["UpdatedAudioMetaInformationDTO"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
