
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./audio-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAllErrors = schemas["AllErrors"];
export type IAudioDTO = schemas["AudioDTO"];
export type IAudioMetaInformationDTO = schemas["AudioMetaInformationDTO"];
export type IAudioSummaryDTO = schemas["AudioSummaryDTO"];
export type IAudioSummarySearchResultDTO = schemas["AudioSummarySearchResultDTO"];
export type IAuthorDTO = schemas["AuthorDTO"];
export type IContributorType = schemas["ContributorType"];
export type ICopyrightDTO = schemas["CopyrightDTO"];
export type ICoverPhotoDTO = schemas["CoverPhotoDTO"];
export type IDescriptionDTO = schemas["DescriptionDTO"];
export type IErrorBody = schemas["ErrorBody"];
export type ILicenseDTO = schemas["LicenseDTO"];
export type IManuscriptDTO = schemas["ManuscriptDTO"];
export type IMetaDataAndFileForm = schemas["MetaDataAndFileForm"];
export type IMetaDataAndOptFileForm = schemas["MetaDataAndOptFileForm"];
export type INewAudioMetaInformationDTO = schemas["NewAudioMetaInformationDTO"];
export type INewPodcastMetaDTO = schemas["NewPodcastMetaDTO"];
export type INewSeriesDTO = schemas["NewSeriesDTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type IPodcastMetaDTO = schemas["PodcastMetaDTO"];
export type ISearchParamsDTO = schemas["SearchParamsDTO"];
export type ISeriesDTO = schemas["SeriesDTO"];
export type ISeriesSearchParamsDTO = schemas["SeriesSearchParamsDTO"];
export type ISeriesSummaryDTO = schemas["SeriesSummaryDTO"];
export type ISeriesSummarySearchResultDTO = schemas["SeriesSummarySearchResultDTO"];
export type ISort = schemas["Sort"];
export type ITagDTO = schemas["TagDTO"];
export type ITagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type ITitleDTO = schemas["TitleDTO"];
export type ITranscriptionResultDTO = schemas["TranscriptionResultDTO"];
export type IUpdatedAudioMetaInformationDTO = schemas["UpdatedAudioMetaInformationDTO"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
