// This file is generated automatically. Do not edit.
import * as openapi from "./concept-api-openapi";
type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type AuthorDTO = schemas["AuthorDTO"];
export type ConceptContent = schemas["ConceptContent"];
export type ConceptDTO = schemas["ConceptDTO"];
export type ConceptSearchParamsDTO = schemas["ConceptSearchParamsDTO"];
export type ConceptSearchResultDTO = schemas["ConceptSearchResultDTO"];
export type ConceptSummaryDTO = schemas["ConceptSummaryDTO"];
export type ConceptTagsDTO = schemas["ConceptTagsDTO"];
export type ConceptTitleDTO = schemas["ConceptTitleDTO"];
export type ContributorType = schemas["ContributorType"];
export type DraftConceptSearchParamsDTO = schemas["DraftConceptSearchParamsDTO"];
export type DraftCopyrightDTO = schemas["DraftCopyrightDTO"];
export type EditorNoteDTO = schemas["EditorNoteDTO"];
export type ErrorBody = schemas["ErrorBody"];
export type GlossDataDTO = schemas["GlossDataDTO"];
export type GlossExampleDTO = schemas["GlossExampleDTO"];
export type LicenseDTO = schemas["LicenseDTO"];
export type Map_List_String = schemas["Map_List_String"];
export type Map_String = schemas["Map_String"];
export type MultiSearchTermsAggregationDTO = schemas["MultiSearchTermsAggregationDTO"];
export type NewConceptDTO = schemas["NewConceptDTO"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type ResponsibleDTO = schemas["ResponsibleDTO"];
export type Sort = schemas["Sort"];
export type StatusDTO = schemas["StatusDTO"];
export type TagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type TermValueDTO = schemas["TermValueDTO"];
export type UpdatedConceptDTO = schemas["UpdatedConceptDTO"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
export type VisualElementDTO = schemas["VisualElementDTO"];
