
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./concept-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAllErrors = schemas["AllErrors"];
export type IAuthorDTO = schemas["AuthorDTO"];
export type IConceptContent = schemas["ConceptContent"];
export type IConceptDTO = schemas["ConceptDTO"];
export type IConceptMetaImageDTO = schemas["ConceptMetaImageDTO"];
export type IConceptResponsibleDTO = schemas["ConceptResponsibleDTO"];
export type IConceptSearchParamsDTO = schemas["ConceptSearchParamsDTO"];
export type IConceptSearchResultDTO = schemas["ConceptSearchResultDTO"];
export type IConceptSummaryDTO = schemas["ConceptSummaryDTO"];
export type IConceptTagsDTO = schemas["ConceptTagsDTO"];
export type IConceptTitleDTO = schemas["ConceptTitleDTO"];
export type IContributorType = schemas["ContributorType"];
export type IDelete = schemas["Delete"];
export type IDraftConceptSearchParamsDTO = schemas["DraftConceptSearchParamsDTO"];
export type IDraftCopyrightDTO = schemas["DraftCopyrightDTO"];
export type IEditorNoteDTO = schemas["EditorNoteDTO"];
export type IErrorBody = schemas["ErrorBody"];
export type IGlossDataDTO = schemas["GlossDataDTO"];
export type IGlossExampleDTO = schemas["GlossExampleDTO"];
export type ILicenseDTO = schemas["LicenseDTO"];
export type IMap_List_String = schemas["Map_List_String"];
export type IMap_String = schemas["Map_String"];
export type IMissing = schemas["Missing"];
export type IMultiSearchTermsAggregationDTO = schemas["MultiSearchTermsAggregationDTO"];
export type INewConceptDTO = schemas["NewConceptDTO"];
export type INewConceptMetaImageDTO = schemas["NewConceptMetaImageDTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type ISort = schemas["Sort"];
export type IStatusDTO = schemas["StatusDTO"];
export type ITagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type ITermValueDTO = schemas["TermValueDTO"];
export type IUpdateOrDelete_NewConceptMetaImageDTO = schemas["UpdateOrDelete_NewConceptMetaImageDTO"];
export type IUpdateOrDelete_String = schemas["UpdateOrDelete_String"];
export type IUpdateWith_NewConceptMetaImageDTO = schemas["UpdateWith_NewConceptMetaImageDTO"];
export type IUpdateWith_String = schemas["UpdateWith_String"];
export type IUpdatedConceptDTO = schemas["UpdatedConceptDTO"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
export type IVisualElementDTO = schemas["VisualElementDTO"];
