
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./frontpage-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAboutFilmSubjectDTO = schemas["AboutFilmSubjectDTO"];
export type IAboutSubjectDTO = schemas["AboutSubjectDTO"];
export type IAllErrors = schemas["AllErrors"];
export type IBannerImageDTO = schemas["BannerImageDTO"];
export type IErrorBody = schemas["ErrorBody"];
export type IFilmFrontPageDTO = schemas["FilmFrontPageDTO"];
export type IFrontPageDTO = schemas["FrontPageDTO"];
export type IMenuDTO = schemas["MenuDTO"];
export type IMenuDataDTO = schemas["MenuDataDTO"];
export type IMovieThemeDTO = schemas["MovieThemeDTO"];
export type IMovieThemeNameDTO = schemas["MovieThemeNameDTO"];
export type INewOrUpdateBannerImageDTO = schemas["NewOrUpdateBannerImageDTO"];
export type INewOrUpdatedAboutSubjectDTO = schemas["NewOrUpdatedAboutSubjectDTO"];
export type INewOrUpdatedFilmFrontPageDTO = schemas["NewOrUpdatedFilmFrontPageDTO"];
export type INewOrUpdatedMetaDescriptionDTO = schemas["NewOrUpdatedMetaDescriptionDTO"];
export type INewOrUpdatedMovieNameDTO = schemas["NewOrUpdatedMovieNameDTO"];
export type INewOrUpdatedMovieThemeDTO = schemas["NewOrUpdatedMovieThemeDTO"];
export type INewOrUpdatedVisualElementDTO = schemas["NewOrUpdatedVisualElementDTO"];
export type INewSubjectPageDTO = schemas["NewSubjectPageDTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type ISubjectPageDTO = schemas["SubjectPageDTO"];
export type IUpdatedSubjectPageDTO = schemas["UpdatedSubjectPageDTO"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
export type IVisualElementDTO = schemas["VisualElementDTO"];
