// This file is generated automatically. Do not edit.
import * as openapi from "./image-api-openapi";
type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type AuthorDTO = schemas["AuthorDTO"];
export type ContributorType = schemas["ContributorType"];
export type CopyMetaDataAndFileForm = schemas["CopyMetaDataAndFileForm"];
export type CopyrightDTO = schemas["CopyrightDTO"];
export type EditorNoteDTO = schemas["EditorNoteDTO"];
export type ErrorBody = schemas["ErrorBody"];
export type ImageAltTextDTO = schemas["ImageAltTextDTO"];
export type ImageCaptionDTO = schemas["ImageCaptionDTO"];
export type ImageDimensionsDTO = schemas["ImageDimensionsDTO"];
export type ImageFileDTO = schemas["ImageFileDTO"];
export type ImageMetaInformationV2DTO = schemas["ImageMetaInformationV2DTO"];
export type ImageMetaInformationV3DTO = schemas["ImageMetaInformationV3DTO"];
export type ImageMetaSummaryDTO = schemas["ImageMetaSummaryDTO"];
export type ImageTagDTO = schemas["ImageTagDTO"];
export type ImageTitleDTO = schemas["ImageTitleDTO"];
export type LicenseDTO = schemas["LicenseDTO"];
export type MetaDataAndFileForm = schemas["MetaDataAndFileForm"];
export type NewImageMetaInformationV2DTO = schemas["NewImageMetaInformationV2DTO"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type SearchParamsDTO = schemas["SearchParamsDTO"];
export type SearchResultDTO = schemas["SearchResultDTO"];
export type SearchResultV3DTO = schemas["SearchResultV3DTO"];
export type Sort = schemas["Sort"];
export type TagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type UpdateImageMetaInformationDTO = schemas["UpdateImageMetaInformationDTO"];
export type UpdateMetaDataAndFileForm = schemas["UpdateMetaDataAndFileForm"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
