
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./image-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAllErrors = schemas["AllErrors"];
export type IAuthorDTO = schemas["AuthorDTO"];
export type IContributorType = schemas["ContributorType"];
export type ICopyMetaDataAndFileForm = schemas["CopyMetaDataAndFileForm"];
export type ICopyrightDTO = schemas["CopyrightDTO"];
export type IDelete = schemas["Delete"];
export type IEditorNoteDTO = schemas["EditorNoteDTO"];
export type IErrorBody = schemas["ErrorBody"];
export type IImageAltTextDTO = schemas["ImageAltTextDTO"];
export type IImageCaptionDTO = schemas["ImageCaptionDTO"];
export type IImageDimensionsDTO = schemas["ImageDimensionsDTO"];
export type IImageFileDTO = schemas["ImageFileDTO"];
export type IImageMetaInformationV2DTO = schemas["ImageMetaInformationV2DTO"];
export type IImageMetaInformationV3DTO = schemas["ImageMetaInformationV3DTO"];
export type IImageMetaSummaryDTO = schemas["ImageMetaSummaryDTO"];
export type IImageTagDTO = schemas["ImageTagDTO"];
export type IImageTitleDTO = schemas["ImageTitleDTO"];
export type ILicenseDTO = schemas["LicenseDTO"];
export type IMetaDataAndFileForm = schemas["MetaDataAndFileForm"];
export type IMissing = schemas["Missing"];
export type INewImageMetaInformationV2DTO = schemas["NewImageMetaInformationV2DTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type ISearchParamsDTO = schemas["SearchParamsDTO"];
export type ISearchResultDTO = schemas["SearchResultDTO"];
export type ISearchResultV3DTO = schemas["SearchResultV3DTO"];
export type ISort = schemas["Sort"];
export type ITagsSearchResultDTO = schemas["TagsSearchResultDTO"];
export type IUpdateImageMetaInformationDTO = schemas["UpdateImageMetaInformationDTO"];
export type IUpdateMetaDataAndFileForm = schemas["UpdateMetaDataAndFileForm"];
export type IUpdateOrDelete_String = schemas["UpdateOrDelete_String"];
export type IUpdateWith_String = schemas["UpdateWith_String"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
