
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./learningpath-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAllErrors = schemas["AllErrors"];
export type IAuthorDTO = schemas["AuthorDTO"];
export type IContributorType = schemas["ContributorType"];
export type ICopyrightDTO = schemas["CopyrightDTO"];
export type ICoverPhotoDTO = schemas["CoverPhotoDTO"];
export type IDescriptionDTO = schemas["DescriptionDTO"];
export type IEmbedUrlV2DTO = schemas["EmbedUrlV2DTO"];
export type IErrorBody = schemas["ErrorBody"];
export type IIntroductionDTO = schemas["IntroductionDTO"];
export type ILearningPathStatusDTO = schemas["LearningPathStatusDTO"];
export type ILearningPathSummaryV2DTO = schemas["LearningPathSummaryV2DTO"];
export type ILearningPathTagsDTO = schemas["LearningPathTagsDTO"];
export type ILearningPathTagsSummaryDTO = schemas["LearningPathTagsSummaryDTO"];
export type ILearningPathV2DTO = schemas["LearningPathV2DTO"];
export type ILearningStepContainerSummaryDTO = schemas["LearningStepContainerSummaryDTO"];
export type ILearningStepSeqNoDTO = schemas["LearningStepSeqNoDTO"];
export type ILearningStepStatusDTO = schemas["LearningStepStatusDTO"];
export type ILearningStepSummaryV2DTO = schemas["LearningStepSummaryV2DTO"];
export type ILearningStepV2DTO = schemas["LearningStepV2DTO"];
export type ILicenseDTO = schemas["LicenseDTO"];
export type IMessageDTO = schemas["MessageDTO"];
export type INewCopyLearningPathV2DTO = schemas["NewCopyLearningPathV2DTO"];
export type INewLearningPathV2DTO = schemas["NewLearningPathV2DTO"];
export type INewLearningStepV2DTO = schemas["NewLearningStepV2DTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type ISearchParamsDTO = schemas["SearchParamsDTO"];
export type ISearchResultV2DTO = schemas["SearchResultV2DTO"];
export type ISort = schemas["Sort"];
export type ITitleDTO = schemas["TitleDTO"];
export type IUpdateLearningPathStatusDTO = schemas["UpdateLearningPathStatusDTO"];
export type IUpdatedLearningPathV2DTO = schemas["UpdatedLearningPathV2DTO"];
export type IUpdatedLearningStepV2DTO = schemas["UpdatedLearningStepV2DTO"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
