// This file is generated automatically. Do not edit.
import * as openapi from "./learningpath-api-openapi";
type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type AuthorDTO = schemas["AuthorDTO"];
export type CommentDTO = schemas["CommentDTO"];
export type ContributorType = schemas["ContributorType"];
export type CopyrightDTO = schemas["CopyrightDTO"];
export type CoverPhotoDTO = schemas["CoverPhotoDTO"];
export type DescriptionDTO = schemas["DescriptionDTO"];
export type EmbedUrlV2DTO = schemas["EmbedUrlV2DTO"];
export type ErrorBody = schemas["ErrorBody"];
export type IntroductionDTO = schemas["IntroductionDTO"];
export type LearningPathStatusDTO = schemas["LearningPathStatusDTO"];
export type LearningPathSummaryV2DTO = schemas["LearningPathSummaryV2DTO"];
export type LearningPathTagsDTO = schemas["LearningPathTagsDTO"];
export type LearningPathTagsSummaryDTO = schemas["LearningPathTagsSummaryDTO"];
export type LearningPathV2DTO = schemas["LearningPathV2DTO"];
export type LearningStepContainerSummaryDTO = schemas["LearningStepContainerSummaryDTO"];
export type LearningStepSeqNoDTO = schemas["LearningStepSeqNoDTO"];
export type LearningStepStatusDTO = schemas["LearningStepStatusDTO"];
export type LearningStepSummaryV2DTO = schemas["LearningStepSummaryV2DTO"];
export type LearningStepV2DTO = schemas["LearningStepV2DTO"];
export type LicenseDTO = schemas["LicenseDTO"];
export type MessageDTO = schemas["MessageDTO"];
export type NewCommentDTO = schemas["NewCommentDTO"];
export type NewCopyLearningPathV2DTO = schemas["NewCopyLearningPathV2DTO"];
export type NewLearningPathV2DTO = schemas["NewLearningPathV2DTO"];
export type NewLearningStepV2DTO = schemas["NewLearningStepV2DTO"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type Priority = schemas["Priority"];
export type ResponsibleDTO = schemas["ResponsibleDTO"];
export type RevisionMetaDTO = schemas["RevisionMetaDTO"];
export type SearchParamsDTO = schemas["SearchParamsDTO"];
export type SearchResultV2DTO = schemas["SearchResultV2DTO"];
export type Sort = schemas["Sort"];
export type TitleDTO = schemas["TitleDTO"];
export type UpdateLearningPathStatusDTO = schemas["UpdateLearningPathStatusDTO"];
export type UpdatedCommentDTO = schemas["UpdatedCommentDTO"];
export type UpdatedLearningPathV2DTO = schemas["UpdatedLearningPathV2DTO"];
export type UpdatedLearningStepV2DTO = schemas["UpdatedLearningStepV2DTO"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
