// This file is generated automatically. Do not edit.
import * as openapi from "./myndla-api-openapi";
type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type BreadcrumbDTO = schemas["BreadcrumbDTO"];
export type ConfigKey = schemas["ConfigKey"];
export type ConfigMetaDTO = schemas["ConfigMetaDTO"];
export type ConfigMetaRestrictedDTO = schemas["ConfigMetaRestrictedDTO"];
export type ConfigMetaValueDTO = schemas["ConfigMetaValueDTO"];
export type CreateRobotDefinitionDTO = schemas["CreateRobotDefinitionDTO"];
export type ErrorBody = schemas["ErrorBody"];
export type ExportedUserDataDTO = schemas["ExportedUserDataDTO"];
export type FolderDTO = schemas["FolderDTO"];
export type FolderDataDTO = schemas["FolderDataDTO"];
export type FolderSortRequestDTO = schemas["FolderSortRequestDTO"];
export type FolderStatus = schemas["FolderStatus"];
export type ListOfRobotDefinitionsDTO = schemas["ListOfRobotDefinitionsDTO"];
export type Map_Long = schemas["Map_Long"];
export type Map_Map_String_Long = schemas["Map_Map_String_Long"];
export type MyNDLAGroupDTO = schemas["MyNDLAGroupDTO"];
export type MyNDLAUserDTO = schemas["MyNDLAUserDTO"];
export type NewFolderDTO = schemas["NewFolderDTO"];
export type NewResourceDTO = schemas["NewResourceDTO"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type OwnerDTO = schemas["OwnerDTO"];
export type ResourceDTO = schemas["ResourceDTO"];
export type ResourceStatsDTO = schemas["ResourceStatsDTO"];
export type ResourceType = schemas["ResourceType"];
export type RobotConfigurationDTO = schemas["RobotConfigurationDTO"];
export type RobotDefinitionDTO = schemas["RobotDefinitionDTO"];
export type RobotSettingsDTO = schemas["RobotSettingsDTO"];
export type RobotStatus = schemas["RobotStatus"];
export type SingleResourceStatsDTO = schemas["SingleResourceStatsDTO"];
export type StatsDTO = schemas["StatsDTO"];
export type UpdatedFolderDTO = schemas["UpdatedFolderDTO"];
export type UpdatedMyNDLAUserDTO = schemas["UpdatedMyNDLAUserDTO"];
export type UpdatedResourceDTO = schemas["UpdatedResourceDTO"];
export type UserFolderDTO = schemas["UserFolderDTO"];
export type UserRole = schemas["UserRole"];
export type UserStatsDTO = schemas["UserStatsDTO"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
