
// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./myndla-api-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type IAllErrors = schemas["AllErrors"];
export type IBreadcrumbDTO = schemas["BreadcrumbDTO"];
export type IConfigKey = schemas["ConfigKey"];
export type IConfigMetaDTO = schemas["ConfigMetaDTO"];
export type IConfigMetaRestrictedDTO = schemas["ConfigMetaRestrictedDTO"];
export type IConfigMetaValueDTO = schemas["ConfigMetaValueDTO"];
export type IEMPLOYEE = schemas["EMPLOYEE"];
export type IErrorBody = schemas["ErrorBody"];
export type IExportedUserDataDTO = schemas["ExportedUserDataDTO"];
export type IFolderDTO = schemas["FolderDTO"];
export type IFolderDataDTO = schemas["FolderDataDTO"];
export type IFolderSortRequestDTO = schemas["FolderSortRequestDTO"];
export type IFolderStatus = schemas["FolderStatus"];
export type IMap_Long = schemas["Map_Long"];
export type IMap_Map_String_Long = schemas["Map_Map_String_Long"];
export type IMyNDLAGroupDTO = schemas["MyNDLAGroupDTO"];
export type IMyNDLAUserDTO = schemas["MyNDLAUserDTO"];
export type INewFolderDTO = schemas["NewFolderDTO"];
export type INewResourceDTO = schemas["NewResourceDTO"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type IOwnerDTO = schemas["OwnerDTO"];
export type IResourceDTO = schemas["ResourceDTO"];
export type IResourceStatsDTO = schemas["ResourceStatsDTO"];
export type IResourceType = schemas["ResourceType"];
export type ISTUDENT = schemas["STUDENT"];
export type ISingleResourceStatsDTO = schemas["SingleResourceStatsDTO"];
export type IStatsDTO = schemas["StatsDTO"];
export type IUpdatedFolderDTO = schemas["UpdatedFolderDTO"];
export type IUpdatedMyNDLAUserDTO = schemas["UpdatedMyNDLAUserDTO"];
export type IUpdatedResourceDTO = schemas["UpdatedResourceDTO"];
export type IUserFolderDTO = schemas["UserFolderDTO"];
export type IUserRole = schemas["UserRole"];
export type IUserStatsDTO = schemas["UserStatsDTO"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationMessage = schemas["ValidationMessage"];
