// This file was generated by OpenApiPlugin, do not edit it manually
import * as openapi from "./oembed-proxy-openapi";

type schemas = openapi.components["schemas"];
export { openapi };

export type AllErrors = schemas["AllErrors"];
export type IAllErrors = schemas["AllErrors"];
export type ErrorBody = schemas["ErrorBody"];
export type IErrorBody = schemas["ErrorBody"];
export type NotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type INotFoundWithSupportedLanguages = schemas["NotFoundWithSupportedLanguages"];
export type OEmbedDTO = schemas["OEmbedDTO"];
export type IOEmbedDTO = schemas["OEmbedDTO"];
export type ValidationErrorBody = schemas["ValidationErrorBody"];
export type IValidationErrorBody = schemas["ValidationErrorBody"];
export type ValidationMessage = schemas["ValidationMessage"];
export type IValidationMessage = schemas["ValidationMessage"];
