package no.ndla.articleapi.db.migration

import no.ndla.articleapi.{TestEnvironment, UnitSuite}

class V53__AddArticleIntroSummaryTest extends UnitSuite with TestEnvironment {
  test("That summary is added to the article") {
    val oldDocument =
      """{"id":null,"slug":null,"tags":[{"tags":["demonstrasjon","fagforening","kvinnebevegelsen","likestilling"],"language":"nb"},{"tags":["demonstrasjon","fagforeining","kvinnerørsla","likestilling"],"language":"nn"}],"title":[{"title":"Likestilling i arbeidslivet gjennom 100 år","language":"nb"},{"title":"Likestilling i arbeidslivet gjennom 100 år","language":"nn"}],"content":[{"content":"<section><ndlaembed data-resource=\"h5p\" data-path=\"/resource/7d70b74a-5771-4d81-865f-6f4ebedc6470\"></ndlaembed></section>","language":"nb"},{"content":"<section><ndlaembed data-resource=\"h5p\" data-path=\"/resource/7d3d3349-4dae-4f3c-8951-de9aca858637\"></ndlaembed></section>","language":"nn"}],"created":"2016-01-18T12:10:07.000Z","updated":"2017-03-06T04:07:53.000Z","revision":1,"copyright":{"origin":"Arbeiderbevegelsens arkiv og bibliotek","license":"CC-BY-NC-SA-4.0","validTo":null,"creators":[{"name":"Vivi Aaslund","type":"Writer"},{"name":"Arbeiderbevegelsens arkiv og bibliotek","type":"Originator"}],"processed":false,"validFrom":null,"processors":[{"name":"Inga Berntsen Rudi","type":"Editorial"}],"rightsholders":[{"name":"Arbeiderbevegelsens arkiv og bibliotek","type":"Supplier"}]},"grepCodes":[],"metaImage":[{"altText":"Fyrstikkarbeiderstreiken 1889. Foto.","imageId":"8338","language":"nb"},{"altText":"Fyrstikkarbeiderstreiken 1889. Foto.","imageId":"8338","language":"nn"}],"published":"2017-03-06T04:07:53.000Z","updatedBy":"r0gHb9Xg3li4yyXv0QSGQczV3bviakrT","conceptIds":[],"articleType":"standard","availability":"everyone","introduction":[],"revisionDate":"2030-01-01T00:00:00.000Z","visualElement":[],"relatedContent":[],"metaDescription":[{"content":"Fra slutten av 1800-tallet ble det satt fokus på kvinners arbeidsvilkår. Vi skal her se på utviklingen gjennom 100 år.","language":"nb"},{"content":"Frå slutten av 1800-talet vart det sett fokus på arbeidsvilkåra til kvinner. Vi skal her sjå på utviklinga gjennom 100 år.","language":"nn"}],"requiredLibraries":[]}"""
    val newDocument =
      """{"id":null,"slug":null,"tags":[{"tags":["demonstrasjon","fagforening","kvinnebevegelsen","likestilling"],"language":"nb"},{"tags":["demonstrasjon","fagforeining","kvinnerørsla","likestilling"],"language":"nn"}],"title":[{"title":"Likestilling i arbeidslivet gjennom 100 år","language":"nb"},{"title":"Likestilling i arbeidslivet gjennom 100 år","language":"nn"}],"content":[{"content":"<section><ndlaembed data-resource=\"h5p\" data-path=\"/resource/7d70b74a-5771-4d81-865f-6f4ebedc6470\"></ndlaembed></section>","language":"nb"},{"content":"<section><ndlaembed data-resource=\"h5p\" data-path=\"/resource/7d3d3349-4dae-4f3c-8951-de9aca858637\"></ndlaembed></section>","language":"nn"}],"created":"2016-01-18T12:10:07.000Z","updated":"2017-03-06T04:07:53.000Z","revision":1,"copyright":{"origin":"Arbeiderbevegelsens arkiv og bibliotek","license":"CC-BY-NC-SA-4.0","validTo":null,"creators":[{"name":"Vivi Aaslund","type":"Writer"},{"name":"Arbeiderbevegelsens arkiv og bibliotek","type":"Originator"}],"processed":false,"validFrom":null,"processors":[{"name":"Inga Berntsen Rudi","type":"Editorial"}],"rightsholders":[{"name":"Arbeiderbevegelsens arkiv og bibliotek","type":"Supplier"}]},"grepCodes":[],"metaImage":[{"altText":"Fyrstikkarbeiderstreiken 1889. Foto.","imageId":"8338","language":"nb"},{"altText":"Fyrstikkarbeiderstreiken 1889. Foto.","imageId":"8338","language":"nn"}],"published":"2017-03-06T04:07:53.000Z","updatedBy":"r0gHb9Xg3li4yyXv0QSGQczV3bviakrT","conceptIds":[],"articleType":"standard","availability":"everyone","introduction":[],"revisionDate":"2030-01-01T00:00:00.000Z","visualElement":[],"relatedContent":[],"metaDescription":[{"content":"Fra slutten av 1800-tallet ble det satt fokus på kvinners arbeidsvilkår. Vi skal her se på utviklingen gjennom 100 år.","language":"nb"},{"content":"Frå slutten av 1800-talet vart det sett fokus på arbeidsvilkåra til kvinner. Vi skal her sjå på utviklinga gjennom 100 år.","language":"nn"}],"requiredLibraries":[],"summary":[{"summary":"","language":"nb"}]}"""
    val migration = new V53__AddArticleIntroSummary
    val result    = migration.convertDocument(oldDocument)
    result should be(newDocument)
  }

}
