name: 'Publish typescript types: image-api'
on:
  push:
    branches:
      - ikkemaster
    paths:
      - image-api/typescript/index.ts
env:
  CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  KNOWIT_EMAIL: ${{ secrets.KNOWIT_EMAIL }}
  COMPONENT: image-api
jobs:
  generate_typescript:
    name: Publish typescript types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '14.16'
      - name: Setup git
        run: |
          git config user.email "$KNOWIT_EMAIL"
          git config user.name "github-actions"
      - name: Publish typescript types
        run: |
          cd image-api/typescript/
          yarn
          yarn build
          yarn publish --non-interactive --access public --patch
          git push
          git push --tags
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
